apiVersion: v1
kind: Service
metadata:
  name: interactive-flix-frontend
spec:
  selector:
    app: interactive-flix-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
